### ISSUE TITLE
Insert Query Builder returns error

### ISSUE THREAD

**Issue by Wilders** [Ang3/php-odoo-api-client#13]
Hello !
I'm trying to convert old requests to DBAL.
I've got this simple create request that works fine : 
```php
$client->create('x_time_line', [
        'x_user' => Auth::user()->name,
        'x_of' => $order['id'],
        'x_start_date' => $start,
        'x_end_date' => date(DATE_ATOM)
]);
```
And I've got the new DBAL request :
```php
$rm->createQueryBuilder('x_time_line')
        ->insert()
        ->setValues([
            'x_user' => Auth::user()->name,
            'x_of' => $order['id'],
            'x_start_date' => $start,
            'x_end_date' => date(DATE_ATOM)
        ])
        ->getQuery()
        ->execute();
```
This DBAL request returns this error : 
TypeError: 'int' object is not iterable (RemoteException)

Do you have any idea on this ?

Thanks !

**Comment by Wilders** [comment]
I've got a similar problem with this update as I'm just incrementing an integer :

```php
            $rm->createQueryBuilder('mrp.production')
                ->update([3])
                ->setValues([
                    'x_studio_qty_produced' => $order['x_studio_qty_produced'] + 1
                ])
                ->getQuery()
                ->execute();
```

Returning : AttributeError: 'list' object has no attribute 'items'.

**Comment by Ang3** [comment]
Hi,

I think it's 2 differents issues.

For the first one, I don't know yet, but could you try to set a where clause for the second?

**Comment by Ang3** [comment]
For first issue, what is the type of each field?

**Comment by Wilders** [comment]
> For the first issue, what is the type of each field?


x_user is text
x_of is many2one on mrp.production
x_start_date is datetime
x_end_date is datetime


> Hi,
> 
> I think it's 2 differents issues.
> 
> For the first one, I don't know yet, but could you try to set a where clause for the second?

What should I add to the where statement ? The id of the row ?



Thanks ! 😄

**Comment by thomasgoemaere** [comment]
Hi,

I'm also having an issue with the create() function.
I'm trying to create a new product template through the RecordManager, my code looks like this:

```
$client->create('product.template',[
      [
              'name' => 'My test product',
              'product_code' => 0,
              'location_code' => 0,
      ]
 ]);
```
When running this code i'm getting the following exception:

**_Exception 'Ang3\Component\Odoo\Exception\RemoteException' with message 'ValueError: dictionary update sequence element #0 has length 1; 2 is required'_**

While I was debugging the QueryBuilder.php file i've noticed that the array of values passed as second argument get's normalized ==> https://github.com/Ang3/php-odoo-api-client/blob/master/src/DBAL/Query/QueryBuilder.php#L464

When replacing this line with `$parameters = $this->values;` everything works fine and the product get's created in Odoo.

So I guess the normalize function isn't necessary for creating records as the function expects key value pairs or am I missing something?

Thanks in advance,
Thomas

**Comment by Wilders** [comment]
> Hi,
> 
> I'm also having an issue with the create() function. I'm trying to create a new product template through the RecordManager, my code looks like this:
> 
> ```
> $client->create('product.template',[
>       [
>               'name' => 'My test product',
>               'product_code' => 0,
>               'location_code' => 0,
>       ]
>  ]);
> ```
> 
> When running this code i'm getting the following exception:
> 
> **_Exception 'Ang3\Component\Odoo\Exception\RemoteException' with message 'ValueError: dictionary update sequence element #0 has length 1; 2 is required'_**
> 
> While I was debugging the QueryBuilder.php file i've noticed that the array of values passed as second argument get's normalized ==> https://github.com/Ang3/php-odoo-api-client/blob/master/src/DBAL/Query/QueryBuilder.php#L464
> 
> When replacing this line with `$parameters = $this->values;` everything works fine and the product get's created in Odoo.
> 
> So I guess the normalize function isn't necessary for creating records as the function expects key value pairs or am I missing something?
> 
> Thanks in advance, Thomas

@Ang3 What do you think about this answer ?

**Comment by Ang3** [comment]
Hi,

Sry I'm working on project so little busy for this end of year.

For the issue of @thomasgoemaere, I think the problem is the embedded array :

```
$client->create('product.template',[
    [
        'name' => 'My test product',
        'product_code' => 0,
        'location_code' => 0,
    ]
]);
```

It should be:

```
$client->create('product.template',[
    'name' => 'My test product',
    'product_code' => 0,
    'location_code' => 0,
]);
```

**Comment by Ang3** [comment]
> > Hi,
> > I'm also having an issue with the create() function. I'm trying to create a new product template through the RecordManager, my code looks like this:
> > ```
> > $client->create('product.template',[
> >       [
> >               'name' => 'My test product',
> >               'product_code' => 0,
> >               'location_code' => 0,
> >       ]
> >  ]);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When running this code i'm getting the following exception:
> > **_Exception 'Ang3\Component\Odoo\Exception\RemoteException' with message 'ValueError: dictionary update sequence element #0 has length 1; 2 is required'_**
> > While I was debugging the QueryBuilder.php file i've noticed that the array of values passed as second argument get's normalized ==> https://github.com/Ang3/php-odoo-api-client/blob/master/src/DBAL/Query/QueryBuilder.php#L464
> > When replacing this line with `$parameters = $this->values;` everything works fine and the product get's created in Odoo.
> > So I guess the normalize function isn't necessary for creating records as the function expects key value pairs or am I missing something?
> > Thanks in advance, Thomas
> 
> @Ang3 What do you think about this answer ?

Hi, can you check your requests on branch ```issue_13```?

**Comment by Ang3** [comment]
@Wilders, were you able to test the fix?

**Comment by Wilders** [comment]
Hi @Ang3.
I'm sorry, I did not see your reply. I will try ASAP when I get back to work.

**Comment by Wilders** [comment]
@Ang3 here is my feedback :
I've tried with this request : 
```
$this->rm->create('time_line', [
    'user' => "test",
....
]);
```
And

```
$this->rm->createQueryBuilder('x_time_line')
    ->insert()
    ->setValues([
        'x_user' => "test",
    ])
    ->getQuery()
    ->execute();

```
and got "ValueError: dictionary update sequence element #0 has length 1; 2 is required"


The update seems to work when using this request : 

```
$this->rm->update('x_time_line', $timeline['id'], [
    'x_end_date' => new DateTime()
]);
```

**Comment by Ang3** [comment]
Thank you, I'll check it in some days ;)

**Comment by thomasgoemaere** [comment]
> > > Hi,
> > > I'm also having an issue with the create() function. I'm trying to create a new product template through the RecordManager, my code looks like this:
> > > ```
> > > $client->create('product.template',[
> > >       [
> > >               'name' => 'My test product',
> > >               'product_code' => 0,
> > >               'location_code' => 0,
> > >       ]
> > >  ]);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > When running this code i'm getting the following exception:
> > > **_Exception 'Ang3\Component\Odoo\Exception\RemoteException' with message 'ValueError: dictionary update sequence element #0 has length 1; 2 is required'_**
> > > While I was debugging the QueryBuilder.php file i've noticed that the array of values passed as second argument get's normalized ==> https://github.com/Ang3/php-odoo-api-client/blob/master/src/DBAL/Query/QueryBuilder.php#L464
> > > When replacing this line with `$parameters = $this->values;` everything works fine and the product get's created in Odoo.
> > > So I guess the normalize function isn't necessary for creating records as the function expects key value pairs or am I missing something?
> > > Thanks in advance, Thomas
> > 
> > 
> > @Ang3 What do you think about this answer ?
> 
> Hi, can you check your requests on branch `issue_13`?
> 
> For your information, we MUST call the method `normalizeData` to format values (dates, collection operations, etc). But iterable and array values was handled differently: keys of iterable values were not preserved (for criteria I guess). I merged handling with basic value formatting. We don't care about criteria keys after all, that's why I send only values from the method `normalizeDomains`.

I overlooked your message to check on branch 'issue_13'.
Just tested this out and seems to work just fine!
Can you tag a new release please :)?
Would be awesome!

Thanks!
