### ISSUE TITLE
Get All Clients

### ISSUE THREAD

**Issue by efraxpc** [Ang3/php-odoo-api-client#2]
Hello, great library! Congrats.

Today I have a question.

How do I can get all odoo products whit this one library?

Thanks

**Comment by Ang3** [comment]
Hi,

Thanks! :-)

If you are talking about product entries in your Odoo database, you just have to use the method ```findBy``` without criteria like below:

```php
$products = $client->findBy('product.product'); // array of products (as array)
```

On odoo database v13.0, the model name of a product is ```product.product```. You should verify this in the configuration (developer mode) in the web interface of your database: ```Technical``` > ```Models``` (on database structure section) - Very useful to get model and fields informations.

**Comment by Ang3** [comment]
Good to know: the method ```findAll``` was added in v5.1.0.
