### ISSUE TITLE
Missing PHP extension ext-xmlrpc

### ISSUE THREAD

**Issue by thomasgoemaere** [Ang3/php-odoo-api-client#20]
Hello,

I'm trying to install the Odoo api client package in my project but i'm getting the following error:

`Root composer.json requires PHP extension ext-xmlrpc * but it is missing from your system. Install or enable PHP's xmlrpc extension.`

I'm running PHP 8.0.14, so it seems that the xmlrpc extension isn't longer installed as a default extension.

Do I need to install it manually? is there like a tutorial I can follow on how to do this?
I suppose this will also be the same for the production environment?

Thanks in advance,
Thomas

**Comment by Ang3** [comment]
Hi,

Idd, sorry but the XMLRPC PHP extension [is not enabled by default anymore on PHP 8](https://php.watch/versions/8.0/xmlrpc). :(

A new release will come very soon in order to avoid using this extension.

**Comment by Ang3** [comment]
An idea to replace XMLRPC dependency: https://github.com/Ang3/php-odoo-api-client/issues/14#issuecomment-880558631

**Comment by Wilders** [comment]
Here is an example for using external API through JSON RPC: https://www.odoo.com/documentation/15.0/developer/howtos/backend.html#json-rpc-library

**Comment by Ang3** [comment]
#24

**Comment by juherr** [comment]
@thomasgoemaere As a workaround, you can add `"phpxmlrpc/polyfill-xmlrpc": "^1.0.0-beta"` as dependency.
Due to https://github.com/gggeek/polyfill-xmlrpc/issues/1 you need to add extra config in your own package too :
```
"replace": {
  "ext-xmlrpc": "*"
},
```
