### ISSUE TITLE
Just updated to v7.0.4

### ISSUE THREAD

**Issue by Wilders** [Ang3/php-odoo-api-client#23]
Hi @Ang3,

I've tried on dev the v7.0.4 release before updating our production servers,

We now got errors on select, like this one :

This select worked well before v7.0.4 : 
```
$orders = $this->rm
                ->createQueryBuilder('mrp.production')
                ->select(['id', 'name', 'product_id', 'x_studio_qty_produced', 'product_qty', 'x_studio_launch'])
                ->where($this->rm->expr()->eq('x_studio_state', 'assembly'))
                ->andWhere($this->rm->expr()->neq('x_studio_launch', false))
                ->andWhere($this->rm->expr()->in('picking_type_id.warehouse_id', array_column((array)$request->getAttribute('token')->loc, 'id')))
                ->andWhere($this->rm->expr()->notIn('state', ['done', 'cancel']))
                ->getQuery()
                ->addOption('context', ['lang' => $request->getAttribute('lang')])
                ->getResult();

```
And now returns:
` TypeError: unhashable type: 'list'`

**Comment by Ang3** [comment]
Hi, sry and thank you for your feedback.
The release has been updated, could you check? Good for me.

**Comment by Wilders** [comment]
@Ang3 Thanks for the fast answer !! It seems to be OK on my side, except that I needed to edit directly in the vendor directory to test it. I couldn't get it from packagist with composer. Maybe you should release again ?

(I've tried to delete the vendor directory and repull again while disabling the cache but it didn't worked)

**Comment by Ang3** [comment]
My fault np, and thank you for your fast answer too! Release done! ;)
