### ISSUE TITLE
Introduced psr/log ^1.1 dependency breaks composer update to use latest working version

### ISSUE THREAD

**Issue by kerbylav** [Ang3/php-odoo-api-client#29]
https://github.com/Ang3/php-odoo-api-client/compare/v7.0.3...v7.0.4#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R24

Due to this dependency introduction, composer installs package of version v7.0.3 instead of latest one if project requires psr/log of versions 2 or 3.

Is it really required dependency? Because package of version v.7.0.3 doesn't work correctly indeed

**Comment by Ang3** [comment]
Hi,

This dependency is for logging so yes I think it's required. But maybe is another way. The version 8.0 is about to be released. When done, I'll check out version ^7.0 to fix it depending on my stuff on 8.0.

**Comment by mbardelmeijer** [comment]
Related issue: https://github.com/Ang3/php-odoo-api-client/issues/31
