### ISSUE TITLE
psr/log 2.0/3.0 support

### ISSUE THREAD

**Issue by mbardelmeijer** [Ang3/php-odoo-api-client#31]
Currently it's locked to ^1.0, where 2.0 & 3.0 both have been released. This blocks upgrading from 7.0.3 to 7.0.6 if psr/log 2.0 or 3.0 is used, as with 7.0.4 this requirement on 1.0 was added.

https://github.com/Ang3/php-odoo-api-client/blob/master/composer.json#L24

**Comment by Ang3** [comment]
#32
