### ISSUE TITLE
Can we specify a network port?

### ISSUE THREAD

**Issue by wdelfuego** [Ang3/php-odoo-api-client#5]
I am trying to get this running locally, using this library from a PHP project on one Vagrant machine to call the Odoo API on another one, both on my own computer. I can ping the Odoo server from the first one and can access Odoo without problems at 192.168.10.19:8069 from my browser.

But, this library is giving me the error: "XML-RPC request failed" when I try to create an object using $client->create($modelName, $data);

I noticed I didn't have to specify the network port in the config of this library, how does that work?  I have to browse to port 8069 if I want to access the web interface locally.

Does this library assume the Odoo API to be available at that port implicitly? I tried changing the URL from just '192.168.10.19' to '192.168.10.19:8069' but that gives the same error.

Hope you can help me along a bit, thank you!!

**Edit:** The underlying Exception says "Cannot access to URL "192.168.10.19/xmlrpc/2/common"

**Comment by Ang3** [comment]
Hi, can you try to add a scheme to your URL, such as ```http://``` or ```https://```?

**Comment by wdelfuego** [comment]
Thanks for your super quick response!
I did that, now I get the error "Bad credentials", so I'm sure that fixed it. Now I feel silly.

Thank you so much!
