### ISSUE TITLE
Count on model

### ISSUE THREAD

**Issue by Wilders** [Ang3/php-odoo-api-client#8]
Hi,

`
$client->count('sale.order');
`
Just wanted to call a count on a model and got this RemoteException : 
(Using Odoo12)
#18 {main}</pre><h2>Previous exception</h2><div><strong>Type:</strong> Ang3\Component\XmlRpc\Exception\RemoteException</div><div><strong>Code:</strong> 1</div><div><strong>Message:</strong> Traceback (most recent call last):
  File &quot;/home/odoo/src/odoo/odoo/addons/base/controllers/rpc.py&quot;, line 69, in xmlrpc_2
    response = self._xmlrpc(service)
  File &quot;/home/odoo/src/odoo/odoo/addons/base/controllers/rpc.py&quot;, line 49, in _xmlrpc
    result = dispatch_rpc(service, method, params)
  File &quot;/home/odoo/src/odoo/odoo/http.py&quot;, line 120, in dispatch_rpc
    result = dispatch(method, params)
  File &quot;/home/odoo/src/odoo/odoo/service/model.py&quot;, line 40, in dispatch
    res = fn(db, uid, *params)
  File &quot;/home/odoo/src/odoo/odoo/service/model.py&quot;, line 178, in execute_kw
    return execute(db, uid, obj, method, *args, **kw or {})
  File &quot;/home/odoo/src/odoo/odoo/service/model.py&quot;, line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File &quot;/home/odoo/src/odoo/odoo/service/model.py&quot;, line 185, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File &quot;/home/odoo/src/odoo/odoo/service/model.py&quot;, line 169, in execute_cr
    result = odoo.api.call_kw(recs, method, args, kw)
  File &quot;/home/odoo/src/odoo/odoo/api.py&quot;, line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File &quot;/home/odoo/src/odoo/odoo/api.py&quot;, line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
TypeError: search_count() missing 1 required positional argument: 'args'

Tried multiple things but I didn't succeed.

**Comment by Ang3** [comment]
Hello,

The Odoo method ```count``` is waiting for criteria, damn!
The version ```6.1.4``` will fix this issue within 24 hours.

Be aware that the release of version ```7.0``` is coming very soon (within 48 hours).
Somes fixes, new features (DBAL), and without this issue of course.

Thank you again for your feedback. :-)

Regards.

**Comment by Wilders** [comment]
Oh yeah, I'm waiting then!

I've seen many little other things:

* Method findAll() isn't in the README
* The method searchOne() isn't the same as in the README (with criteria and options)
* Same for the method search() (with criteria = null by default)

Keep doing what you do ! :)

Much thanks.

**Comment by Ang3** [comment]
Fixed with version ```7.0```. ;)
